### ISSUE TITLE
Using backslash in branch name

### ISSUE THREAD

**Issue by nitzano** [robvanderleek/create-issue-branch#136]
Hello, I've tried to create a branch that looks like `feature/{ISSUE_NUMBER}/{ISSUE_TITLE}`
by using the following configuration:

```yml
branchName: '${issue.number}/${issue.title}'
branches:
  - label: bug
    prefix: bug/
  - label: "*"
    prefix: "feature/"
```

However the backslash  charcter got replaced and the branch was eventually:
`feature/yyy-title` instead of `feature/yyy/title`.

What's the correct setting to enable backslash in branch name template?
