### ISSUE TITLE
Feature Request: Add ability to prevent branch creation for label type

### ISSUE THREAD

**Issue by nthomas20** [robvanderleek/create-issue-branch#167]
I would like to be able to prevent automatic branch creation on issue assignment for certain label types.

E.g. For our organization, a `question` label assignment is intended to pose a question to a particular individual for discussion only. In this situation a branch may not be required. The ability to defer or ignore automatic branch creation would be helpful.

**Comment by robvanderleek** [comment]
Hi @nthomas20 

Thanks for the feedback.

Currently it's possible to configure the source branch and branch name prefix based on an issue label, for example:
```
branches:
  - label: enhancement
    name: dev
    prefix: feature/
  - label: bug
    name: staging
    prefix: bugfix/
```
It should be easy to add an option like `ignore` or `skip` to this configuration to exclude labels from automatic branch creation.
Would that work for you? Any preference on the option name?

Rob
