### ISSUE TITLE
Bug Report: Issues not creating branches

### ISSUE THREAD

**Issue by tfeuerbach** [robvanderleek/create-issue-branch#186]
I've copied the sample doc into my .github and branches are not being created. 
```
on:
    issues:
        types: [assigned]
    issue_comment:
        types: [created]

jobs:
    create_issue_branch_job:
        mode: chatops
        runs-on: ubuntu-latest
        steps:
        - name: Create Issue Branch
          uses: robvanderleek/create-issue-branch@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I've also installed it from the marketplace as an action and am having the same issue. Any help would be greatly appreciated!
