### ISSUE TITLE
Feature request: multi-level rule definition

### ISSUE THREAD

**Issue by TGTGamer** [robvanderleek/create-issue-branch#219]
So I'm creating a monorepository, with automatic deployments based on branch information. So for instance `feat/webfront/{title}` might automatically be deployed to my development system. As it stands, I use a lot of automation to try and decrease the time it takes my dev team to manage projects, this includes automatic labelling based on the issue title and such. 

_So my workflow:_
User submits a issue with title `feat(webdocs): add new documentation for featX`
My automation automatically detects `feat` and `webdocs` and assigns label `Type - Feature` & `Package - Webdocs` using personal token
At this point a second workflow would be triggered which creates branch using this action. The branch that would be generated is `feat/${issue.number}-add-new-documentation-for-featX` 

**Proposed Changes**
What I would love to be able to do is have multi-level rules. Which look something like:

```yaml
mode: auto
silent: false
branchName: '${issue.number}-${issue.title}'
autoCloseIssue: true
branches:
  - label: 'Type - Feature'
    prefix: feat/
    extra:
      label: 'Package - Webdocs'
      prefix: webdocs/
```

This would allow me to create more complex and sophisticated branches, making it much easier to maintain a large Mono Repository. The above example would output `feat/webdocs/${issue.number}-add-new-documentation-for-featX`

**Comment by robvanderleek** [comment]
Thanks for the detailed explanation @TGTGamer 

An alternative to your proposal would be to support lists of labels in the branch configuration YAML.
For example, the configuration to support your branching scheme above would then be:

```yaml
mode: auto
silent: false
branchName: '${issue.number}-${issue.title}'
autoCloseIssue: true
branches:
  - label: 
    - 'Type - Feature'
    - 'Package - Webdocs'
    prefix: feat/webdocs/
  - label: 'Type - Feature'
    prefix: feat/
```

I'm aware this leads to more duplication of configuration code but it keeps the configuration structure a bit less complex and it's also easier to implement.

Would this work for your use-case?
