### ISSUE TITLE
How to implement other options in yml file?

### ISSUE THREAD

**Issue by rupertbulquerin** [robvanderleek/create-issue-branch#251]
I got a line error when trying to implement the other options.

I want to implement this
```
gitSafeReplacementChar: '-' 

branchName: '${issue.number}-${issue.title}'

          branches:
            - label: enhancement
              prefix: feature/
            - label: bug
              prefix: bugfix/
            - label: '*'
              prefix: issues/
            - label: question
              skip: true
            - label: documentation
              skip: true
            - label: duplicate
              skip: true
            - label: help wanted
              skip: true
            - label: invalid
              skip: true 
```

this is my yml file.

```
name: Create Issue Branch


on:
    issues:
        types: [assigned]
    issue_comment:
        types: [created]

jobs:
    create_issue_branch_job:
        runs-on: ubuntu-latest
        steps:
        - name: Create Issue Branch
          id: Create_Issue_Branch
        - uses: robvanderleek/create-issue-branch@v1.3
          gitSafeReplacementChar: '-'   # got underline error here
          branchName: '${issue.number}-${issue.title}'   # got underline error here
          branches:   # got underline error here
            - label: enhancement
              prefix: feature/
            - label: bug
              prefix: bugfix/
            - label: '*'
              prefix: issues/
            - label: question
              skip: true
            - label: documentation
              skip: true
            - label: duplicate
              skip: true
            - label: help wanted
              skip: true
            - label: invalid
              skip: true 
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Echo branch name
          run: echo ${{ steps.Create_Issue_Branch.outputs.branchName }}
```

**Comment by robvanderleek** [comment]
Hi @rupertbulquerin 

The configuration for this App can't be done directly in the GitHub Action YAML.
You need to add a configuration YAML to your repo: `.github/issue-branch` and move the lines:

```yaml
    gitSafeReplacementChar: '-'
    branchName: '${issue.number}-${issue.title}'
    branches:
      - label: enhancement
        prefix: feature/
      - label: bug
        prefix: bugfix/
      - label: '*'
        prefix: issues/
      - label: question
        skip: true
      - label: documentation
        skip: true
      - label: duplicate
        skip: true
      - label: help wanted
        skip: true
      - label: invalid
        skip: true 
```

to that file.

It's also possible to have an organization/user wide configuration YAML.

Please see the [Configuration section in the README](https://github.com/robvanderleek/create-issue-branch#configuration)

KR, Rob
