### ISSUE TITLE
Branches `prefix` arguments won't create correct branch folder

### ISSUE THREAD

**Issue by shiipou** [robvanderleek/create-issue-branch#322]
Hi, I want to use your GitHub Action to automatically create the branch, but When I use the `type | feature` label, the workflow create a branch named `bug/issue-1-something` instead of `feature/issue-1-something`.

Can you help me to configure it correctly ?

Here my config file : 

```yaml
gitSafeReplacementChar: '-'
autoCloseIssue: true

branches:
  - label: 'type | bug'
    prefix: bug/
    name: latest
  - label: 'type | documentation'
    prefix: documentation/
    name: latest
  - label: 'type | feature'
    prefix: feature/
    name: latest
  - label: 'type | maintenance'
    prefix:  maintenance/
    name: latest
```

Thank you very much for the help.
