### ISSUE TITLE
linked PR does not show actor that typed in cib command

### ISSUE THREAD

**Issue by ajRiverav** [robvanderleek/create-issue-branch#329]
Hi!

Is there a way for the gh action to link the PR as the actor who initiated the `/cib`?

The screenshot below shows user 1 initiating the /cib but it shows user 2 linked it. 

![1](https://user-images.githubusercontent.com/22076301/106811926-66e51d80-6645-11eb-8d3c-cf18c62c19b9.png)

**Comment by ajRiverav** [comment]
cc: @robvanderleek!

**Comment by robvanderleek** [comment]
Hi @ajRiverav 

Sorry for the late reply.

Do you inject a Personal Access Token (PAT) into the action in your workflow file? In that case all the activities from the action are linked to your GitHub account. If you don't use a PAT all activities are linked to the `github-actions[bot]` account.

I guess both cases do not work for your situation, unfortunately there is no way (I know of) to link a PR created by the action to a different user (for example the user that added the `/cib` comment).

**Comment by ajRiverav** [comment]
> Hi @ajRiverav
> 
> Sorry for the late reply.
> 
> Do you inject a Personal Access Token (PAT) into the action in your workflow file? In that case all the activities from the action are linked to your GitHub account. If you don't use a PAT all activities are linked to the `github-actions[bot]` account.
> 
> I guess both cases do not work for your situation, unfortunately there is no way (I know of) to link a PR created by the action to a different user (for example the user that added the `/cib` comment).

ah, yes. I do inject a PAT generated under my account.

**Comment by ajRiverav** [comment]
so, here's what I have done. 

I've removed `env: <PAT>` from the bottom of this file.

```
name: "Create issue branch"
on:
  issue_comment:
    types: [created]
    branches:
      - "!develop"
  pull_request:
    types: [closed]
jobs:
  create_issue_branch_job:
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@master
```

Typing `/cib` did trigger the action but a PR was not created. Observe this "chatops" 
comment in the GH Actions log: 

```
Run robvanderleek/create-issue-branch@master
2
INFO	 (probot): App was loaded
3
INFO	 (probot): Skipping Sentry.io setup
4
INFO	 (probot): Total memory: 93 Mb
5
INFO	 (probot): ChatOps command received
6
INFO	 (probot): Received ChatOps command but current mode is not `chatops`, exiting
```

However, upon verifying this setting. I do have it: 

```
# create new PR by typing /cib as a comment.
mode: chatops
# branch name format
branchName: "${issue.number}_${issue.title,}"
gitSafeReplacementChar: "-"
# by default the app comments on the issue after creating a branch.
silent: true
commentMessage: "Branch ${branchName} created"
# close issue when closing this PR
autoCloseIssue: true
# always open in draft state
openDraftPR: true
```
