### ISSUE TITLE
Trigger the bot after adding a label

### ISSUE THREAD

**Issue by shekari-ah** [robvanderleek/create-issue-branch#351]
let's assume I assigned a person to an issue, and that person decided to create a branch for that. I set the wildcat to create a branch on `has PR` labels, but after assigning a person, adding a label doesn't trigger the bot to create a new branch.

I also add this code to the workflow, but that didn't work:
```yml
on:
    issues:
        types: [assigned, labeled]
```

**Comment by shekari-ah** [comment]
I look at your code and figure out you don't have any event for `labeled`.
I can help you to add this feature if you want.

**Comment by robvanderleek** [comment]
Hi @shekari-ah 

You are right, the App code does currently not handle `labeled` events.

It might be a bit tricky to implement for support for this. The App now has [2 modes](https://github.com/robvanderleek/create-issue-branch#usage) in which it is activated: after assigning an issue or after giving a ChatOps command in the issue comments.
Do you suggest to add another mode for labels?

**Comment by shekari-ah** [comment]
no, use that for the auto mode.

 **I create an issue and assign it to a teammate. after discussion, he decided to create a PR for the issue. now he has to assign the issue again to trigger the bot. or he can simply add a `has PR` label and the bot will be triggered to create a branch.**

the bot will be triggered every time there a change in the labels and act base on the rules of the labels. 
```yml
branches:
  - label: enhancement
    prefix: feature/
  - label: bug
    prefix: bugfix/
  - label: '*'
    prefix: issues/
```
the bot will not make another branch if there is already one.

we can add a setting to disable this action, something like this:
```yml
triggerOnLabeled: false
```
