### ISSUE TITLE
Problems with automatic branches and pull requests

### ISSUE THREAD

**Issue by Kazan1520** [robvanderleek/create-issue-branch#352]
While making an issue, the branch is created from a right branch, but the pull request is wrong. For example when i make an issue, a new branch is created from my develop branch, but the pull request goes to master instead of develop.
My configs:
 issue-branch.yml
```
autoCloseIssue: true
branches:
  - label: refactor
    name: develop
    prefix: refactor/
  - label: enhancement
    name: develop
    prefix: enhancement/
openDraftPR: true
```
main.yml
```
on:
    issues:
        types: [assigned]
    issue_comment:
        types: [created]
    pull_request:
        types: [closed]
jobs:
  create_branch:
    runs-on: ubuntu-latest
    name: Create Branch
    steps:
        - name: Create Issue Branch
          uses: robvanderleek/create-issue-branch@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}`
```
