### ISSUE TITLE
Created branch in different repository when organization wide action

### ISSUE THREAD

**Issue by jezscha** [robvanderleek/create-issue-branch#425]
At the moment the action is creating only a branch, PR or draftPR at the repository in which it has been created. But wouldn't it be also useful to be able to tell in job filters which repos it should be created? 

In following example you could see two more atributes of a job. `issue-repos` is list where each repo issue is triggering the job. `target-repo` is single name of repo where a branch, PR or draftPR should be created.  

I understand the comlexity might feel to be unnecessary but this is how we are dealing with client's issues. Those are mirrored automatically from Freshdesk app and as we don't want to show clients data at public opensource repository, we are keeping them separatelly.  
 
```yaml
jobs:
    create_issue_branch_job:
        issue-repos: [client-issues-repo, bug-tracking-repo]
        target-repo: dev-repo
        runs-on: ubuntu-latest
        steps:
        - name: Create Issue Branch
          uses: robvanderleek/create-issue-branch@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
