### ISSUE TITLE
Fallback Prefix?

### ISSUE THREAD

**Issue by Mike-EEE** [robvanderleek/create-issue-branch#49]
Hey there... cool looking app. :)  I was wondering if there is a way to set a default/fallback prefix for values configured.

Essentially, if there isn't a label that matches, I would like to create a branch that looks like `issues/i<id>` where `<id>` is the issue number.

Something like:

```
branches:
  - label: enhancement
    prefix: feature/
  - label: bug
    prefix: bugfix/
  - label: *
    prefix: issues/
```

Thank you for any assistance/consideration. 👍

**Comment by robvanderleek** [comment]
Hi @Mike-EEE 

Thanks for your feedback.

Not too hard to implement, have your example config working, but I'm not sure about the exact syntax.
Asterisk has a special meaning in YAML, so the config needs to look like:
```
branches:
  ...
  - label: bug
    prefix: bugfix/
  - label: '*'
    prefix: issues/
```
Maybe it's best to quote all string values in the YAML examples anyway:
```
branches:
  ...
  - label: 'bug'
    prefix: 'bugfix/'
  - label: '*'
    prefix: 'issues/'
```
Another option is to have `defaultPrefix` as a separate field, but then I think there needs to be a field for `defaultName` as well:
```
branches:
  ...
  - label: bug
    prefix: bugfix/
  defaultPrefix: issues/
  defaultBranch: dev
```
This might be a bit confusing as GitHub has the notion of a "default branch" as well.

What do you think?
