### ISSUE TITLE
Draft PR not created.

### ISSUE THREAD

**Issue by gw-ubunye** [robvanderleek/create-issue-branch#506]
I have added the file "issue-branch.yml" to my repo:

![image](https://user-images.githubusercontent.com/47982867/139051258-8f06e9de-41a2-4228-9c85-19c53c73b763.png)

with this content:

```yaml
openDraftPR: true

branches:
  - label: duplicate
    skip: true

  - label: wontfix
    skip: true
    
  - label: invalid
    skip: true
```

After I had done this, I created a new issue (none of the labels above were applied) and the branch was created but the draft PR was not. We are on the "GitHub Team" plan which includes draft PRs.

Is there anything else I have to configure or is there a log to see what went wrong?

Thanks,
Gerhard.
