### ISSUE TITLE
[Documentation]  Disable unused github action triggers

### ISSUE THREAD

**Issue by leovigna** [robvanderleek/create-issue-branch#512]
The current documentation on the README uses the following trigger configuration:
```
on:
  issues: #default mode
    types: [ assigned ]
  issue_comment: #chatops mode
    types: [ created ]
  pull_request:
    types: [ closed ]
```
However, if I'm not mistaken, the bot only needs one of the `issues` or `issue_comment` depending on whether it's running on default or chatops mode. For example, I use chat ops so commenting out the `issues [assigned]` trigger avoids having unecessary actions triggered on Github.

I suggest updating the documentation to a more optimal configuration depending on the user's use case.
