### ISSUE TITLE
Bug not auto-opening PRs

### ISSUE THREAD

**Issue by uyeonyx** [robvanderleek/create-issue-branch#747]
<img width="408" alt="image" src="https://github.com/robvanderleek/create-issue-branch/assets/65580604/d69b2e85-f261-4dec-a3b4-51b96ad89d01">

hello.
I am utilizing your project very well.

So far, I have done hundreds of automated branches and PR creation, but I have encountered one unexplained issue.

It failed to create the PR and output an error with the message `Could not create PR (Not Found)`

I didn't do anything special, and I didn't identify any specific reproduction steps that caused the problem.
We just created an issue, assigned an assignee, and assigned a feature label and other ancillary labels.

Here is my issue-branch.yaml in full

```yaml
defaultBranch: 'develop'
branchName: '${issue.number}:${issue.title,}'
gitSafeReplacementChar: '-'
branches:
  - label : feature
    prefix: feature/
    name: develop
    prTarget: develop
    skip: false
  - label : bug
    prefix: bugfix/
    name: develop
    prTarget: develop
    skip: false
  - label : critical
    prefix: hotfix/
    name: master
    prTarget: master
    skip: false
  - label : 'release: staging'
    prefix: release-staging/
    name: develop
    prTarget: release
    skip: false
  - label : 'release: production'
    prefix: release-production/
    name: release
    prTarget: master
    skip: false
  - label : '*'
    skip: true


prSkipCI: true
copyIssueDescriptionToPR: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
openDraftPR: true
commentMessage: "✅ Work Branch Created!\n```git checkout ${branchName}```\ncopy this 👆"
autoCloseIssue: true
```
