### ISSUE TITLE
Bug where issues created by Convert to issue in Project did not trigger actions

### ISSUE THREAD

**Issue by uyeonyx** [robvanderleek/create-issue-branch#771]
Hi, @robvanderleek 👋

Thanks for adding `skipBranch` the [other day](https://github.com/robvanderleek/create-issue-branch/issues/748).
It's been really helpful.

Good to see you again.

---

I am using a mix of [GH Project](https://docs.github.com/en/issues/planning-and-tracking-with-projects/creating-projects/creating-a-project) with your product in my enterprise.
For the most part, I think everything works beautifully with no issues, but there is one issue.
I am able to create a Draft via Add Item in a project.
And I can convert the draft to an issue via `Convert to issue`.
The issue will be created in the repository where `create-issue-branch` is installed.
The problem with this is that the issue will not automatically create a PR, even if the assignor and labeling are chosen correctly.
Conversely, when you create an issue in the repository, link it to a project and expose it, everything works fine.

I'm attaching a screenshot for better understanding.

---
![image](https://github.com/robvanderleek/create-issue-branch/assets/65580604/162e184d-22fb-46fc-a08c-409be18d0d2d)
![image](https://github.com/robvanderleek/create-issue-branch/assets/65580604/46b8d4e3-70de-44cd-9fbe-fc80a7f6ed6a)

Create an issue by creating a Draft and selecting a repository via `Convert to issue`, as shown in the first image.

I then specify `Assignees` and `Labels` to make create-issue-branch work.

However, as you can see in the second image, nothing happens.
(Even after reassigning the assignees and labels, it still doesn't work).

---

![image](https://github.com/robvanderleek/create-issue-branch/assets/65580604/97514ce9-9e63-4822-aaba-72af1d194ec2)

However, if I just create an issue in the repository and link it to your project like you've always done, it will (of course) work and look great.

---

Here's my `issue-branch.yaml`.

```yaml
defaultBranch: 'develop'
branchName: '${issue.number}:${issue.title,}'
gitSafeReplacementChar: '-'
branches:
  - label : feature
    prefix: feature/
    name: develop
    prTarget: develop
    skip: false
  - label : bug
    prefix: bugfix/
    name: develop
    prTarget: develop
    skip: false
  - label : critical
    prefix: hotfix/
    name: master
    prTarget: master
    skip: false
  - label : 'release: staging'
    name: develop
    prTarget: release
    skipBranch: true
    skip: false
  - label : 'release: production'
    name: release
    prTarget: master
    skipBranch: true
    skip: false
  - label : '*'
    skip: true


prSkipCI: true
copyIssueDescriptionToPR: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
openDraftPR: true
commentMessage: "✅ Work Branch Created!\n```git checkout ${branchName}```\ncopy this 👆"
autoCloseIssue: true
```
