### ISSUE TITLE
branchName not going working?

### ISSUE THREAD

**Issue by ReneTC** [robvanderleek/create-issue-branch#824]
Not sure if I am setting the `branchName` wrong in the .yml file. This is my config:
```
on:
  # The issue.opened event below is only needed for the "immediate" mode.
  # The issue.assigned event below is only needed for the default ("auto") mode.
  issues:
    types: [ opened, assigned ]
  # The issue_comment.created event below is only needed for the ChatOps mode.
  issue_comment:
    types: [ created ]
  # The pull_request events below are only needed for pull-request related features.
  pull_request:
    types: [ opened, closed ]

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@main
        with:
          branchName: '${issue.number}-${issue.title}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```
This runs and works.. however, it seems to ignore the branchName variable, as the branch name appends "issue" to the name.. So I have the branch name:  'issue-${issue.number}-${issue.title}'.

Is it setup wrongly? thanks for the input

I also asked here: https://stackoverflow.com/questions/78204904/settings-for-a-github-actions-yml-file-create-issue-branch
