### ISSUE TITLE
No branch created after create an issue with a tag

### ISSUE THREAD

**Issue by andychowhh** [robvanderleek/create-issue-branch#837]
My repo structure
```
.github
   - workflows
      - issue-branch.yml
   - issue-branch.yml
```

.github/workflows/issue-branch.yml
```
name: Create Issue Branch

on:
  issues:
    types: [opened]

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Echo branch name
        run: echo ${{ steps.Create_Issue_Branch.outputs.branchName }}
```

.github/issue-branch.yml
```
mode: immediate
branchName: full
defaultBranch: 'master'
autoLinkIssue: true
autoCloseIssue: false
createPR: true
branches:
  - label: enhancement
    prefix: feature/
  - label: bug
    prefix: bugfix/
```

Steps to reproduce
1. Create a new issue with `bug` tag -> Click **Submit New Issue** button
2. Go Actions tab to check and It's completed
![Screenshot 2024-04-22 at 5 36 27 PM](https://github.com/robvanderleek/create-issue-branch/assets/99651284/c485dc21-809e-4cfa-b870-39c7a0389f36)
![Screenshot 2024-04-22 at 5 36 58 PM](https://github.com/robvanderleek/create-issue-branch/assets/99651284/551981b7-74da-4315-9139-c05ab908173d)

**Comment by robvanderleek** [comment]
Hi @andychowhh 

Sorry to hear the action is not working for you.

I recreated your setup in [this repository](https://github.com/facio-ergo-sum/test-repo-create-issue-branch-prod-action) with [this action run](https://github.com/facio-ergo-sum/test-repo-create-issue-branch-prod-action/actions/runs/8796049184/job/24138178541).

I suspect a branch *is* created. There's a small error in your workflow: the Create Issue Branch step needs an ID so the next step can refer back to it:

```yaml
      - name: Create Issue Branch
        id: Create_Issue_Branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Echo branch name
        run: echo ${{ steps.Create_Issue_Branch.outputs.branchName }}
```

The `Creating comment failed` error you get might be caused by the permission of your `GITHUB_TOKEN`. Can you please check `Settings > Actions > General > Workflow permissions` in the repository where you're running this action?
The permissions need to be read and write (I believe that's the default, or maybe GitHub changed this default). 

<img width="786" alt="image" src="https://github.com/robvanderleek/create-issue-branch/assets/5324924/92621537-f45c-4ad6-a5d2-fd060f6bea83">

HTH, Rob
