### ISSUE TITLE
Branch not created

### ISSUE THREAD

**Issue by OoBook** [robvanderleek/create-issue-branch#954]
The workflow proceeds properly up to last step, but it prints warnings, and did not create the issue branch. The event of workflow is 'issue on labeled' 

When I remove create-issue-branch and create a branch with git commands everything works fine. But your action does not create the branch.

For instance;
steps.branch_name.outputs.branch: fix-login-page-oauth2-issue-101
steps.prefix.outputs.prefix: bugfix

```
on:
  issues:
    types: [labeled]
```

```
    - name: Create Issue Branch
        if: steps.prefix.outputs.prefix != ''
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          autoCloseIssue: true
          autoLinkIssue: true
          branchName: '${{ steps.prefix.outputs.prefix }}${{ steps.branch_name.outputs.branch }}'
          defaultBranch: ${{ steps.prefix.outputs.source }}
```

Workflow logs as following:

<img width="944" alt="Screenshot 2024-12-11 at 12 21 21" src="https://github.com/user-attachments/assets/dd5d6202-961b-4426-a2bc-7145892bf9cf">
